### ISSUE TITLE
Doesn't work on Arch Linux

### ISSUE THREAD

**Issue by quentindemetz** [chef/opscode-omnitruck#77] opened 2015-01-19 10:07 UTC
I've finally been able to install on my workstation (https://github.com/opscode/omnibus/pull/367), but I can't yet provision EC2 nodes with knife-ec2:
```
ec2-54-74-70-113.eu-west-1.compute.amazonaws.com Unable to determine platform version!
ec2-54-74-70-113.eu-west-1.compute.amazonaws.com Version: 12
```

**Comment by rychipman** [comment] 2015-01-31 21:21
Arch Linux is not a platform supported by omnitruck. See [here](https://docs.chef.io/api_omnitruck.html) for a list of supported platforms and other API information.

I too have run into this issue (trying to use test kitchen in my case) and am planning to patch in arch support and submit a PR.

**Comment by rychipman** [comment] 2015-02-01 22:56
So to quote <code>install.sh</code>, 

    This should now match ohai platform and platform_version matching

But this is not the case, since ohai actually recognizes archlinux now (although it does not correctly set something for platform_version, hence my PR #473)

I am writing a patch to make install.sh function like ohai in this regard.

**Comment by rychipman** [comment] 2015-02-01 23:36
Nevermind. Thoroughly examining install.sh shows a comment stating that arch (along with a bunch of other distros) will not be supported due to a lack of build infrastructure. Therefore, omnitruck will not work on arch, and this is not really a bug.

So this should probably be closed.

**Comment by lamont-granquist** [comment] 2015-02-02 03:58
Yeah there's install instructions for arch here:

https://wiki.archlinux.org/index.php/Chef

Since arch is a rolling distro you can probably also just gem install it.  The major point of omnibus is to deal with CentOS5 and other ancient distros with out of date rubies and openssls which we didn't have any time to debug.  At least on arch you're likely to be more ahead of us than 10 years behind us.

**Comment by lamont-granquist** [comment] 2015-04-16 22:31
closing because this is not a bug, and not really useful for prioritizing build platforms.

getting involved in IRC in the community meetings and the RFC process and lobbying for arch support there would be more useful.

**Closed by lamont-granquist** 2015-04-16 22:31 UTC
