### ISSUE TITLE
bash: line 111: chef-client: command not found on install.sh

### ISSUE THREAD

**Issue by vbp11** [chef/opscode-omnitruck#96] opened 2015-05-05 19:56 UTC
Hi, 
am trying to bootstrap a node from my work station using knife command, but getting error such as 
'bash: line 111: chef-client: command not found'. have proxy settings which allows me to access opscode.com or chef.io, so its not an proxy issue, so could you please guide me how do i resolve it.
here in the attached snapshot:
devrepo1 node is my workstation
10.50.100.37 is my chef-client which needs to bootstrap.
and using chef DK Version 0.4.0
and chef 12

![install sh-snapshot](https://cloud.githubusercontent.com/assets/11964456/7481420/b73c6a1c-f33d-11e4-9bba-67286a7a1281.PNG)
please guide me bootstrap a node on chef client using chef12

Thanks,
Ven.

**Comment by lamont-granquist** [comment] 2015-05-14 20:03
The problem is the "connection refused" error two lines earlier.   If you have a proxy you probably need to pass `--bootstrap-proxy` to knife bootstrap.

**Comment by lamont-granquist** [comment] 2015-06-19 16:26
Closing this as can't replicate and probably a networking setup error

**Closed by lamont-granquist** 2015-06-19 16:26 UTC
